In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
# import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

In [2]:
dataset = pd.read_csv('3bIris.csv')

In [3]:
dataset.shape

(150, 6)

In [4]:
X=dataset.iloc[:,:4].values

In [5]:
X

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [9]:
Y=dataset['Species'].values
Y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2)

In [28]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 1.10512788,  2.3392095 , -0.52563118,  1.69712654],
       [-1.4465303 , -0.03224344,  2.24692887, -1.50316922],
       [ 1.01062202,  2.3392095 , -0.98772452,  1.81350094],
       [-0.52509818, -0.40668338, -1.68086453,  0.12607226],
       [ 0.51446627,  0.46700981, -0.2945845 ,  0.30063384],
       [ 0.30182809, -0.28187006, -0.06353783,  0.18425945],
       [-0.69048343, -0.90593663,  1.78483553, -1.27042044],
       [ 0.65622505,  0.59182312, -0.2945845 ,  1.05706739],
       [ 0.67985152,  0.84144975, -0.06353783,  1.17344178],
       [ 0.1600693 , -0.03224344, -0.75667785,  0.06788506],
       [ 0.4908398 , -0.15705675, -0.2945845 ,  0.24244665],
       [-1.23389211, -0.90593663,  0.62960218, -1.21223325],
       [-0.43059232, -1.15556325, -1.44981786, -0.28123811],
       [-0.57235111,  0.71663644,  0.39855551,  0.41700824],
       [-0.47784525, -0.15705675, -0.52563118,  0.41700824],
       [ 1.24688667,  0.71663644, -0.52563118,  1.05706739],
       [-1.70642141, -1.

In [31]:
classifier = GaussianNB()
classifier.fit(X_train,Y_train)

GaussianNB()

In [32]:
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [33]:
cm=confusion_matrix(Y_test,y_pred)
cm

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  0, 11]], dtype=int64)

In [34]:
print("Accuracy : ",accuracy_score(Y_test,y_pred))

Accuracy :  1.0


In [35]:
df=pd.DataFrame({'Real':Y_test,'Predicted':y_pred})
df

Real        Predicted
0    Iris-virginica   Iris-virginica
1    Iris-virginica   Iris-virginica
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4   Iris-versicolor  Iris-versicolor
5    Iris-virginica   Iris-virginica
6   Iris-versicolor  Iris-versicolor
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13   Iris-virginica   Iris-virginica
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16      Iris-setosa      Iris-setosa
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21   Iris-virginica   Iris-virginica
22   Iris-virginica   Iris-virginica
23      Iris-setosa      Iris-setosa
24      Iris-setosa      Iris-setosa
25  Iris-versicolor  Iris-versicolor
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa